---
- hosts: server2.abc.com
  become: yes
  remote_user: test
  gather_facts: no
  tasks:
      - include: install.yml
      - include: copy.yml
      - include: service.yml
- hosts: server3.abc.com
  become: yes
  roles:
    - webservers
    - geerlingguy.git

