---
- hosts: server2.abc.com
  become: yes
  tasks:
     - name: Install httpd package
       yum: name={{item}} state=installed
       with_items:
          - httpd
          - curl
       ignore_errors: yes
     - name: create user
       user: 
          name: "{{item.name}}"
          state: present
          groups: "{{item.groups}}"
       with_items:
          - { name: 'ravi', groups: 'ravi'}
          - { name: 'xyx', groups: 'ravi'}
       delegate_to: localhost
