---
# tasks file for webservers
- name: Install httpd package
  yum: name={{pkg}} state=installed
- name: copy index.html
  copy: src=index.html  dest=/var/www/html
  notify: restart httpd service
- name: start httpd service
  service: name=httpd state=started

